In [7]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)


[5 7 9]
[ 4 10 18]


In [6]:
array = np.array([1,2,3,4,5,6])
print(f'Array sum: {np.sum(array)}')
print(f'array Mean: {np.mean(array)}')
print(f'Standard Deviation: {np.std(array)}')

Array sum: 21
array Mean: 3.5
Standard Deviation: 1.707825127659933


In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [10]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [11]:
array = np.array([1,2,3,4,5,6])
normalized_data = (array-np.min(array))/(np.max(array)-np.min(array))
print(f'Normalized array: {normalized_data}')

Normalized array: [0.  0.2 0.4 0.6 0.8 1. ]


In [19]:
a = np.array([1, 2, 3, 4])
b = a[2:4]
b[0] = 100
print(a)

[  1   2 100   4]


In [22]:
#linear algebra
# 3x + y = 9
# x + 2y = 8
# Ax = b
a = np.array([[3,1],[1,2]])
b = np.array([[9],[8]])
print(np.linalg.solve(a,b))

[[2.]
 [3.]]
