In [16]:
import numpy as np
array2d = np.array([[1,2,3],[4,5,6]])
column_sum = np.sum(array2d, axis=0) #
row_sum = np.sum(array2d, axis=1)
print(f'Column sum: {column_sum}\nRow sum: {row_sum}')


Column sum: [5 7 9]
Row sum: [ 6 15]


In [14]:
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,2)
print(f'Split array: {split_array}')
sum = np.sum(split_array,axis=0)
print(sum)

Split array: [array([1, 2, 3]), array([4, 5, 6])]
[5 7 9]


In [21]:
zeros_array = np.zeros((3,3))
print(f'Zeros array: {zeros_array}')

Zeros array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
reshape_array = array.reshape(3,2)
print(f'Reshape array: {reshape_array}')

Reshape array: [[1 2]
 [3 4]
 [5 6]]
